export enum SortKey {
  RELEASE_DATE = 'RELEASE_DATE',
  RATING = 'RATING',
  TITLE_DESC = 'TITLE_DESC',
  TITLE_ASC = 'TITLE_ASC',
  INGEST_ASC = 'INGEST_ASC',
  INGEST_DESC = 'INGEST_DESC',
  RANDOM = 'RANDOM',
  NOT_SORTED = 'NOT_SORTED',
}
